# Etapa 1: Construção
FROM node:18 AS builder

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos necessários para o container
COPY package.json package-lock.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Compila o projeto Next.js para produção
RUN npm run build

# Etapa 2: Execução
FROM node:18-alpine

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos necessários da etapa de construção
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package.json /app/package-lock.json ./

# Instala apenas as dependências necessárias para produção
RUN npm install --production

# Define a porta que o container vai expor
EXPOSE 3000

# Comando para iniciar o servidor Next.js
CMD ["npm", "start"]