version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8051:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
